### ISSUE TITLE
Change the github link in footer to point to our github org

### ISSUE THREAD

**Issue by masonj5n** [kidsoncomputers/website#13]
The "GitHub" link in our footer points to `https://github.com/facebook/docusaurus`
![image](https://github.com/kidsoncomputers/website/assets/25966620/684564cc-ce3d-43bf-97dc-e4a426fe792f)

We should switch it to point to `https://github.com/kidsoncomputers`

The footer can be updated in the `docusaurus.config.js` file.

**Comment by PatriceRoot** [comment]
can i work on this issue ?

**Comment by PatriceRoot** [comment]
It's already good, please close this issue @masonj5n

**Comment by randytate** [comment]
👍🏼
